/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BasicRide {
  'dropOffLocation' : string,
  'userId' : Principal,
  'rideTime' : Time,
  'pickupLocation' : string,
}
export interface Coordinates { 'lat' : number, 'long' : number }
export interface PricingPlan {
  'features' : Array<string>,
  'name' : string,
  'price' : bigint,
}
export interface RideRequest {
  'dropOffLocation' : string,
  'rideTime' : Time,
  'pickupLocation' : string,
}
export interface RiderProfile {
  'name' : string,
  'isAvailable' : boolean,
  'photoUrl' : string,
  'distance' : number,
  'rating' : number,
  'coordinates' : [] | [Coordinates],
}
export type Time = bigint;
export interface UserProfile {
  'name' : string,
  'email' : [] | [string],
  'phone' : [] | [string],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addRiderProfile' : ActorMethod<[string, RiderProfile], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'bookRide' : ActorMethod<[RideRequest], boolean>,
  'getAllPricingPlans' : ActorMethod<[], Array<PricingPlan>>,
  'getAllRiders' : ActorMethod<[], Array<RiderProfile>>,
  'getAllRides' : ActorMethod<[], Array<BasicRide>>,
  'getAllRidesInternal' : ActorMethod<[], Array<BasicRide>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getNearbyRides' : ActorMethod<[Coordinates, number], Array<RiderProfile>>,
  'getRidesForUser' : ActorMethod<[Principal], Array<BasicRide>>,
  'getUserPosition' : ActorMethod<
    [Principal],
    { 'notAvailable' : null } |
      { 'location' : Coordinates }
  >,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'initialize' : ActorMethod<[string, string], undefined>,
  'initializeSeedData' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateAvailableRiders' : ActorMethod<[], Array<RiderProfile>>,
  'updateRiderLocation' : ActorMethod<[string, Coordinates], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];