/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Coordinates = IDL.Record({
  'lat' : IDL.Float64,
  'long' : IDL.Float64,
});
export const RiderProfile = IDL.Record({
  'name' : IDL.Text,
  'isAvailable' : IDL.Bool,
  'photoUrl' : IDL.Text,
  'distance' : IDL.Float64,
  'rating' : IDL.Float64,
  'coordinates' : IDL.Opt(Coordinates),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const RideRequest = IDL.Record({
  'dropOffLocation' : IDL.Text,
  'rideTime' : Time,
  'pickupLocation' : IDL.Text,
});
export const PricingPlan = IDL.Record({
  'features' : IDL.Vec(IDL.Text),
  'name' : IDL.Text,
  'price' : IDL.Nat,
});
export const BasicRide = IDL.Record({
  'dropOffLocation' : IDL.Text,
  'userId' : IDL.Principal,
  'rideTime' : Time,
  'pickupLocation' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Opt(IDL.Text),
  'phone' : IDL.Opt(IDL.Text),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addRiderProfile' : IDL.Func([IDL.Text, RiderProfile], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'bookRide' : IDL.Func([RideRequest], [IDL.Bool], []),
  'getAllPricingPlans' : IDL.Func([], [IDL.Vec(PricingPlan)], ['query']),
  'getAllRiders' : IDL.Func([], [IDL.Vec(RiderProfile)], ['query']),
  'getAllRides' : IDL.Func([], [IDL.Vec(BasicRide)], ['query']),
  'getAllRidesInternal' : IDL.Func([], [IDL.Vec(BasicRide)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getNearbyRides' : IDL.Func(
      [Coordinates, IDL.Float64],
      [IDL.Vec(RiderProfile)],
      ['query'],
    ),
  'getRidesForUser' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(BasicRide)],
      ['query'],
    ),
  'getUserPosition' : IDL.Func(
      [IDL.Principal],
      [IDL.Variant({ 'notAvailable' : IDL.Null, 'location' : Coordinates })],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'initialize' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'initializeSeedData' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateAvailableRiders' : IDL.Func([], [IDL.Vec(RiderProfile)], []),
  'updateRiderLocation' : IDL.Func([IDL.Text, Coordinates], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Coordinates = IDL.Record({ 'lat' : IDL.Float64, 'long' : IDL.Float64 });
  const RiderProfile = IDL.Record({
    'name' : IDL.Text,
    'isAvailable' : IDL.Bool,
    'photoUrl' : IDL.Text,
    'distance' : IDL.Float64,
    'rating' : IDL.Float64,
    'coordinates' : IDL.Opt(Coordinates),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const RideRequest = IDL.Record({
    'dropOffLocation' : IDL.Text,
    'rideTime' : Time,
    'pickupLocation' : IDL.Text,
  });
  const PricingPlan = IDL.Record({
    'features' : IDL.Vec(IDL.Text),
    'name' : IDL.Text,
    'price' : IDL.Nat,
  });
  const BasicRide = IDL.Record({
    'dropOffLocation' : IDL.Text,
    'userId' : IDL.Principal,
    'rideTime' : Time,
    'pickupLocation' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Opt(IDL.Text),
    'phone' : IDL.Opt(IDL.Text),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addRiderProfile' : IDL.Func([IDL.Text, RiderProfile], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'bookRide' : IDL.Func([RideRequest], [IDL.Bool], []),
    'getAllPricingPlans' : IDL.Func([], [IDL.Vec(PricingPlan)], ['query']),
    'getAllRiders' : IDL.Func([], [IDL.Vec(RiderProfile)], ['query']),
    'getAllRides' : IDL.Func([], [IDL.Vec(BasicRide)], ['query']),
    'getAllRidesInternal' : IDL.Func([], [IDL.Vec(BasicRide)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getNearbyRides' : IDL.Func(
        [Coordinates, IDL.Float64],
        [IDL.Vec(RiderProfile)],
        ['query'],
      ),
    'getRidesForUser' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(BasicRide)],
        ['query'],
      ),
    'getUserPosition' : IDL.Func(
        [IDL.Principal],
        [IDL.Variant({ 'notAvailable' : IDL.Null, 'location' : Coordinates })],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'initialize' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'initializeSeedData' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateAvailableRiders' : IDL.Func([], [IDL.Vec(RiderProfile)], []),
    'updateRiderLocation' : IDL.Func([IDL.Text, Coordinates], [], []),
  });
};

export const init = ({ IDL }) => { return []; };